// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZnux-qh_Km_1ZvIJMdxY1uS11MphluZ8',
    appId: '1:268632801026:web:01a128fca97862d88d4c1b',
    messagingSenderId: '268632801026',
    projectId: 'papeleria-parelib',
    authDomain: 'papeleria-parelib.firebaseapp.com',
    databaseURL: 'https://papeleria-parelib-default-rtdb.firebaseio.com',
    storageBucket: 'papeleria-parelib.appspot.com',
    measurementId: 'G-42W4RH2PM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOA9fLt-BNTurAhjzS2kc4h3VX15piZ4o',
    appId: '1:268632801026:android:b5b3c39a978c9a0f8d4c1b',
    messagingSenderId: '268632801026',
    projectId: 'papeleria-parelib',
    databaseURL: 'https://papeleria-parelib-default-rtdb.firebaseio.com',
    storageBucket: 'papeleria-parelib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSeNqNMcSvWqdJbIUS8y23mKNmi5AGGL8',
    appId: '1:268632801026:ios:2663fa3ae41c4a068d4c1b',
    messagingSenderId: '268632801026',
    projectId: 'papeleria-parelib',
    databaseURL: 'https://papeleria-parelib-default-rtdb.firebaseio.com',
    storageBucket: 'papeleria-parelib.appspot.com',
    iosBundleId: 'com.parelib.papeleriaParelib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSeNqNMcSvWqdJbIUS8y23mKNmi5AGGL8',
    appId: '1:268632801026:ios:5bd13dcd8c3de6608d4c1b',
    messagingSenderId: '268632801026',
    projectId: 'papeleria-parelib',
    databaseURL: 'https://papeleria-parelib-default-rtdb.firebaseio.com',
    storageBucket: 'papeleria-parelib.appspot.com',
    iosBundleId: 'com.parelib.papeleriaParelib.RunnerTests',
  );
}
